# Generated by Django 4.2.1 on 2023-05-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_job_job_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="description",
            field=models.TextField(default="", max_length=1000),
            preserve_default=False,
        ),
    ]
