# Generated by Django 4.2.1 on 2023-05-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_job_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="experience",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="job",
            name="published_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="job",
            name="salary",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="job",
            name="vacancy",
            field=models.IntegerField(default=1),
        ),
    ]
